import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadPinnedPayload as ContractsThreadPinnedPayloadSchema,
  ThreadUnpinnedPayload as ContractsThreadUnpinnedPayloadSchema,
  ThreadPinReorderedPayload as ContractsThreadPinReorderedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  ProjectScheduleCreatedPayload as ContractsProjectScheduleCreatedPayloadSchema,
  ProjectScheduleUpdatedPayload as ContractsProjectScheduleUpdatedPayloadSchema,
  ProjectSchedulePausedPayload as ContractsProjectSchedulePausedPayloadSchema,
  ProjectScheduleResumedPayload as ContractsProjectScheduleResumedPayloadSchema,
  ProjectScheduleDeletedPayload as ContractsProjectScheduleDeletedPayloadSchema,
  ProjectScheduleRunRequestedPayload as ContractsProjectScheduleRunRequestedPayloadSchema,
  ScheduleOccurrenceStartedPayload as ContractsScheduleOccurrenceStartedPayloadSchema,
  ScheduleOccurrenceCompletedPayload as ContractsScheduleOccurrenceCompletedPayloadSchema,
  ScheduleOccurrenceFailedPayload as ContractsScheduleOccurrenceFailedPayloadSchema,
  ScheduleOccurrenceSkippedPayload as ContractsScheduleOccurrenceSkippedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;
export const ThreadPinnedPayload = ContractsThreadPinnedPayloadSchema;
export const ThreadUnpinnedPayload = ContractsThreadUnpinnedPayloadSchema;
export const ThreadPinReorderedPayload = ContractsThreadPinReorderedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;

export const ProjectScheduleCreatedPayload = ContractsProjectScheduleCreatedPayloadSchema;
export const ProjectScheduleUpdatedPayload = ContractsProjectScheduleUpdatedPayloadSchema;
export const ProjectSchedulePausedPayload = ContractsProjectSchedulePausedPayloadSchema;
export const ProjectScheduleResumedPayload = ContractsProjectScheduleResumedPayloadSchema;
export const ProjectScheduleDeletedPayload = ContractsProjectScheduleDeletedPayloadSchema;
export const ProjectScheduleRunRequestedPayload = ContractsProjectScheduleRunRequestedPayloadSchema;
export const ScheduleOccurrenceStartedPayload = ContractsScheduleOccurrenceStartedPayloadSchema;
export const ScheduleOccurrenceCompletedPayload = ContractsScheduleOccurrenceCompletedPayloadSchema;
export const ScheduleOccurrenceFailedPayload = ContractsScheduleOccurrenceFailedPayloadSchema;
export const ScheduleOccurrenceSkippedPayload = ContractsScheduleOccurrenceSkippedPayloadSchema;
